# Generated by Django 4.2.7 on 2024-01-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveSmallIntegerField(default=0)),
                ('type', models.PositiveSmallIntegerField(choices=[(6, 'Drama'), (1, 'Horror'), (3, 'Action'), (0, 'Other'), (2, 'Sci-fi'), (5, 'Comedy'), (4, 'Romantic')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='bonus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_films.moreinfo'),
        ),
    ]
