# Generated by Django 4.2.7 on 2024-01-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_films', '0002_moreinfo_film_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(6, 'Drama'), (1, 'Horror'), (4, 'Romantic'), (2, 'Sci-fi'), (5, 'Comedy'), (3, 'Action'), (0, 'Other')], default=0),
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='')),
                ('stars', models.PositiveSmallIntegerField(default=5)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_films.film')),
            ],
        ),
    ]
