# Generated by Django 4.2.7 on 2024-01-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_films', '0003_alter_moreinfo_type_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moreinfo',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Action'), (2, 'Sci-fi'), (5, 'Comedy'), (4, 'Romantic'), (1, 'Horror'), (0, 'Other'), (6, 'Drama')], default=0),
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('surname', models.CharField(max_length=32)),
                ('films', models.ManyToManyField(to='app_films.film')),
            ],
        ),
    ]
